# Base
FROM registry.access.redhat.com/ubi9/go-toolset:1.22 AS build

WORKDIR /app
USER root

# Copy the application source code (not included in this repo)
COPY app/ .

# Build the Go application
RUN go build -o cities-app

# Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

WORKDIR /app

# Copy the compiled binary from the build stage
COPY --from=build /app/cities-app .

# Expose the application port
EXPOSE 8090

# Start the application
ENTRYPOINT ["/app/cities-app"]

