FROM registry.ocp4.example.com:8443/redhattraining/podman-ubi9.5

WORKDIR /tmp/hello-server

COPY . .

RUN dnf module enable -y nodejs:22 && \
    dnf install -y nodejs npm && \
    npm install

CMD npm start 

